version: "3.9"

services:
  web:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: havuk1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: